### ISSUE TITLE
Questions about the future

### ISSUE THREAD

**Issue by hurnhu** [web-pyjs/v4f#51]
Is there plans to add support for custom validators?
is there plans for remote validation?

**Comment by reyx7** [comment]
Yes, I will work for this rule as soon as possible.

Thanks for your feedback.

**Comment by reyx7** [comment]
@hurnhu What do you mean by remote validation, can you explain more?

**Comment by reyx7** [comment]
@hurnhu , custom validator is implemented.
you can check https://v4f.js.org/docs/api-reference/rules/generic#custom-options in documentation web site how to use custom rule.

**Comment by hurnhu** [comment]
what i ment about remote validation is server side validation.
