### ISSUE TITLE
Passing related field's value in custom function

### ISSUE THREAD

**Issue by zysktomasz** [web-pyjs/v4f#57]
Lately I've been wondering and trying to make custom function that could use value of some other related field.

I'm fine using custom validators in custom(), but can't figure out if it's possible to pass 
```js
["#someField"]
```
inside that custom validator, like
```js
Field().custom(someNotYetWorkingValidator(["#someField"]))
```

To be more precise - I have two datepickers in my form and would like to validate their dates (later/earlier etc.)

I'm not experienced in js, but looking at source code, it doesn't seem to be possible just because how custom() is written.
```js
export const custom = (fun, value) => fun(value);
```

Could you provide me with some tips? (i've been thinking about forking and trying to add some additional lines, but maybe I'm missing some existing solution)

**Comment by nsoufian** [comment]
@zysktomasz You want to pass a function that can manipulate related rules if you see the documentation of related field you can see that you can pass another element to the array as a callback that get related-field data as input and must return a value.

```javascript
Field().custom(["#someField", x => x.Uppercase()], callbackValidator);
```

**Comment by chrisneal** [comment]
@reyx7 That doesn't work. The callbackValidator never gets called. Any ideas?

**Comment by nsoufian** [comment]
@chrisneal can you make a sandbox for these issues

**Comment by chrisneal** [comment]
@reyx7 https://codesandbox.io/s/3km1h

**Comment by nsoufian** [comment]
@chrisneal  it works correctly, the costum rule only takes an array with two elements the  ["Field Name", callback_function], check out the [API reference](https://v4f.js.org/docs/api-reference/rules/generic#custom-options) for more information.

If your problem is not resolved open a new issue with detailed pieces of information, that will help to workaround the issue.

@chrisneal  thanks for your feedback

**Comment by chrisneal** [comment]
@reyx7 In your reply to zysktomasz above, you mention that you can use a custom field with a callback, and then an additional callback.

```js
Field().custom(
  [
    "#someField", 
    x => x.Uppercase()
  ], 
  callbackValidator
);
```

In my sandbox example, I have:
```js
Field().custom(
  [
    "#endedAt",
    endedAt => {
      console.log(endedAt);
      return true;
    }
  ],
  startedAt => {
    console.log(startedAt);
    return true;
  }
)
```

So are you saying that your reply to zysktomasz is incorrect?

**Comment by nsoufian** [comment]
@chrisneal Please read the documentation carefully.

**Comment by chrisneal** [comment]
@reyx7 I have... Could you at least answer my question?

**Comment by nsoufian** [comment]
@chrisneal please give some time to the documentation and try to understand the library,
and try the examples in the documentation.

**Comment by chrisneal** [comment]
@reyx7 I have read the documentation, and looked through the code. I was purely referencing your comment above. I can't see any evidence of it working the way it does above, but you're the author, and you're the one that gave the example code. So I'm assuming that the code in your comment above is wrong?

**Comment by nsoufian** [comment]
@chrisneal  can you please make a clear example in the sandbox , the library is fine all rules are well tested you have miss understood something.

**Comment by chrisneal** [comment]
@reyx7 I posted a sandbox link above (https://codesandbox.io/s/3km1h), as well as called out the specific code from my sandbox here:
https://github.com/web-pyjs/v4f/issues/57#issuecomment-494711196
